name: .NET Deploy to Github Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --configuration Release --output build
    - name: ls
      run: ls ./Blazor_NobuPortfolioApp/bin/Release/net6.0/publish/wwwroot/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./Blazor_NobuPortfolioApp/bin/Release/net6.0/publish/wwwroot/
